### ISSUE TITLE
performance not so great on large files

### ISSUE THREAD

**Issue by coldnebo** [meh/ruby-mbox#22]
parsing a 32M mbox file promptly hung on this line (from ruby trace):

```
#0:/Library/Ruby/Gems/2.0.0/gems/mbox-0.1.0/lib/mbox/mail/content.rb:38:Mbox::Mail::Content:-:      if type && type.mime && type.boundary && matches = type.mime.match(%r{multipart/(\w+)})
#0:/Library/Ruby/Gems/2.0.0/gems/mbox-0.1.0/lib/mbox/mail/content.rb:39:Mbox::Mail::Content:-:          text.sub(/^.*?--#{type.boundary}\n/m, '').sub(/--#{type.boundary}--$/m, '').split("--#{type.boundary}\n").each {|part|
^C#0:/Library/Ruby/Gems/2.0.0/gems/mbox-0.1.0/lib/mbox/mail/content.rb:39:String:^:             text.sub(/^.*?--#{type.boundary}\n/m, '').sub(/--#{type.boundary}--$/m, '').split("--#{type.boundary}\n").each {|part|
#0:/Library/Ruby/Gems/2.0.0/gems/mbox-0.1.0/lib/mbox/mail/content.rb:39:Mbox::Mail::Content:<:          text.sub(/^.*?--#{type.boundary}\n/m, '').sub(/--#{type.boundary}--$/m, '').split("--#{type.boundary}\n").each {|part|
#
```

It's not clear from the doc whether there is a way of paging over messages with large attachments.  I'm using the stream interface, but it appears to want to parse the entire email message on most operations.

Running through tracer, It seems that split line is creating a large number of substrings... maybe an attached pdf or something.

Going to take a look at node-mbox in the meantime for a faster streaming solution.

**Comment by meh** [comment]
You can pass a parameter to `#each` to request it only reads headers and not contents: `mbox.each(headers_only: true)`.

Now whether that's working as intended or bugged is another story :panda_face: 

I constantly read a bunch of mboxes where the average size is 200M and it's not that bad.

**Comment by coldnebo** [comment]
awesome, worked like a charm! thx
